-- ============================================================
-- Справочник типов разъёмов (connector_types)
-- Генерируется из connector_types.json, не редактировать вручную
-- ============================================================

CREATE TABLE connector_types (
  code        VARCHAR(32) PRIMARY KEY,
  name        VARCHAR(64) NOT NULL,
  name_ru     VARCHAR(64),
  category    VARCHAR(16) NOT NULL
              CHECK (category IN ('video','audio','network','data','control','power','wireless')),
  layer       VARCHAR(16) NOT NULL
              CHECK (layer IN ('physical','protocol','wireless')),
  color       VARCHAR(7)  NOT NULL,
  line_style  VARCHAR(8)  NOT NULL DEFAULT 'solid'
              CHECK (line_style IN ('solid','dashed')),
  notes       TEXT,
  created_at  TIMESTAMP NOT NULL DEFAULT now(),
  updated_at  TIMESTAMP NOT NULL DEFAULT now()
);

-- синонимы для фаззи-матчинга при AI-извлечении спеков оборудования
CREATE TABLE connector_type_aliases (
  connector_code VARCHAR(32) NOT NULL REFERENCES connector_types(code) ON DELETE CASCADE,
  alias          VARCHAR(128) NOT NULL,
  PRIMARY KEY (connector_code, alias)
);

-- физический(е) носитель(и) для протокольных типов (Dante/NDI/AES67/Art-Net/sACN -> Ethernet)
CREATE TABLE connector_type_carriers (
  protocol_code VARCHAR(32) NOT NULL REFERENCES connector_types(code) ON DELETE CASCADE,
  physical_code VARCHAR(32) NOT NULL REFERENCES connector_types(code) ON DELETE CASCADE,
  PRIMARY KEY (protocol_code, physical_code)
);

-- ------------------------------------------------------------
-- seed data
-- ------------------------------------------------------------

INSERT INTO connector_types (code, name, name_ru, category, layer, color, line_style, notes) VALUES
  ('HDMI', 'HDMI', 'HDMI', 'video', 'physical', '#3F3F3F', 'solid', NULL),
  ('SDI', 'SDI', 'SDI', 'video', 'physical', '#6FA8DC', 'solid', NULL),
  ('DISPLAYPORT', 'DisplayPort', 'DisplayPort', 'video', 'physical', '#E8B647', 'solid', NULL),
  ('DVI', 'DVI', 'DVI', 'video', 'physical', '#B8860B', 'solid', NULL),
  ('VGA', 'VGA', 'VGA', 'video', 'physical', '#4A4A4A', 'solid', NULL),
  ('GENLOCK', 'Genlock / black burst', 'Генлок', 'video', 'physical', '#8C8C8C', 'solid', 'Физически тот же BNC-разъём, что у SDI, но это сигнал синхронизации, не видеопоток — выделен отдельным типом, чтобы валидатор не спутал sync-порт с видео-портом.'),
  ('FIBER', 'Fiber optic', 'Оптика', 'data', 'physical', '#CC0000', 'solid', 'Оптика — это среда передачи; конкретный сигнал поверх неё (SDI-extender, Ethernet, гибридный кабель) уточняется на уровне оборудования.'),
  ('XLR', 'XLR', 'XLR', 'audio', 'physical', '#6FCF4D', 'solid', NULL),
  ('RCA', 'RCA', 'RCA (тюльпан)', 'audio', 'physical', '#1B7A1B', 'solid', 'Используется и для аналогового аудио, и для композитного видео — категория здесь ''audio'' как основная.'),
  ('JACK', 'Jack (TRS/TS)', 'Джек', 'audio', 'physical', '#2DD4C4', 'solid', NULL),
  ('XLR_JACK', 'XLR/Jack combo', 'XLR/Джек комбо', 'audio', 'physical', '#26C2B3', 'solid', NULL),
  ('MINI_JACK', 'Mini-jack', 'Мини-джек', 'audio', 'physical', '#0F9D77', 'solid', NULL),
  ('AES_EBU', 'AES/EBU', 'AES/EBU', 'audio', 'physical', '#3D8B8B', 'solid', 'Физически обычно XLR (балансный) либо BNC 75 Ом (проф. вариант).'),
  ('TOSLINK', 'Toslink (optical audio)', 'Тослинк', 'audio', 'physical', '#D4622D', 'solid', NULL),
  ('SPDIF_COAX', 'S/PDIF coaxial', 'S/PDIF (коакс)', 'audio', 'physical', '#C97A3D', 'solid', NULL),
  ('SPEAKON', 'Speakon', 'Спикон', 'audio', 'physical', '#7B1FA2', 'solid', NULL),
  ('DANTE', 'Dante (audio over IP)', 'Dante', 'audio', 'protocol', '#00A7B5', 'solid', 'Физический разъём — RJ45/Ethernet, но это отдельный протокол. При валидации соединений сверяйте protocol-тип, а не только физический разъём.'),
  ('AES67', 'AES67 (audio over IP)', 'AES67', 'audio', 'protocol', '#008C99', 'solid', 'Как и Dante, физически Ethernet — отдельный протокол поверх него.'),
  ('MIDI', 'MIDI', 'MIDI', 'control', 'physical', '#CC1111', 'solid', 'Классический разъём — 5-pin DIN. Современные устройства часто туннелируют MIDI через USB (см. тип USB).'),
  ('DMX', 'DMX512', 'DMX', 'control', 'physical', '#E08080', 'solid', NULL),
  ('ARTNET', 'Art-Net', 'Art-Net', 'control', 'protocol', '#D88A4A', 'solid', 'DMX-данные внутри обычного Ethernet — физически RJ45.'),
  ('SACN', 'sACN', 'sACN', 'control', 'protocol', '#CC8B52', 'solid', 'Аналогично Art-Net — DMX-данные поверх Ethernet, другой протокол.'),
  ('RS232', 'RS-232', 'RS-232', 'control', 'physical', '#707070', 'solid', NULL),
  ('RS485', 'RS-485', 'RS-485', 'control', 'physical', '#5C5C5C', 'solid', NULL),
  ('ETHERNET', 'Ethernet', 'Ethernet', 'network', 'physical', '#1C4FA0', 'solid', NULL),
  ('ETHERCON', 'EtherCon', 'Эзеркон', 'network', 'physical', '#1C4FA0', 'solid', 'Электрически идентичен RJ45/Ethernet, отличается только защищённым корпусом разъёма — для валидации совместим с ETHERNET.'),
  ('USB', 'USB', 'USB', 'data', 'physical', '#D946C0', 'solid', NULL),
  ('USB_C', 'USB-C', 'USB-C', 'data', 'physical', '#C13FB0', 'solid', NULL),
  ('THUNDERBOLT', 'Thunderbolt', 'Thunderbolt', 'data', 'physical', '#6A1B9A', 'solid', NULL),
  ('FIREWIRE', 'FireWire', 'FireWire', 'data', 'physical', '#C0C0C0', 'solid', NULL),
  ('LIGHTNING', 'Lightning', 'Lightning', 'data', 'physical', '#4CD964', 'solid', NULL),
  ('NDI', 'NDI (video over IP)', 'NDI', 'video', 'protocol', '#2A9DF4', 'solid', 'Физически RJ45/Ethernet, отдельный протокол видео поверх IP — не путать порт NDI с обычным сетевым портом при валидации.'),
  ('POWER', 'Power (generic AC)', 'Питание (общее)', 'power', 'physical', '#2E5FA8', 'solid', NULL),
  ('POWERCON', 'PowerCon', 'Пауэркон', 'power', 'physical', '#E040FB', 'solid', NULL),
  ('IEC', 'IEC C13/C14', 'IEC разъём', 'power', 'physical', '#4A4A90', 'solid', NULL),
  ('SCHUKO', 'Schuko', 'Шуко', 'power', 'physical', '#3A6FB5', 'solid', NULL),
  ('EDISON', 'Edison (NEMA)', 'Эдисон', 'power', 'physical', '#2D5FA0', 'solid', NULL),
  ('BANANA', 'Banana plug', 'Банан', 'power', 'physical', '#B5651D', 'solid', 'Используется и в силовых, и в акустических (колонки) соединениях.'),
  ('TERMINAL_BLOCK', 'Terminal block', 'Терминальный блок', 'power', 'physical', '#8C6E4A', 'solid', NULL),
  ('WIRELESS', 'Wireless (generic RF)', 'Беспроводное', 'wireless', 'wireless', '#7CA8DC', 'dashed', 'Обобщённый тип для радиоканала без конкретного протокола. Если важен протокол — используйте WIFI или BLUETOOTH.'),
  ('WIFI', 'Wi-Fi', 'Wi-Fi', 'wireless', 'wireless', '#5B9BD5', 'dashed', NULL),
  ('BLUETOOTH', 'Bluetooth', 'Bluetooth', 'wireless', 'wireless', '#2F5FCB', 'dashed', NULL);

INSERT INTO connector_type_aliases (connector_code, alias) VALUES
  ('HDMI', 'High-Definition Multimedia Interface'),
  ('SDI', 'HD-SDI'),
  ('SDI', '3G-SDI'),
  ('SDI', '6G-SDI'),
  ('SDI', '12G-SDI'),
  ('SDI', 'Serial Digital Interface'),
  ('SDI', 'BNC video'),
  ('DISPLAYPORT', 'DP'),
  ('DISPLAYPORT', 'Mini DisplayPort'),
  ('DVI', 'Digital Visual Interface'),
  ('DVI', 'DVI-D'),
  ('DVI', 'DVI-I'),
  ('DVI', 'DVI-A'),
  ('VGA', 'D-Sub 15'),
  ('VGA', 'D-Sub HD15'),
  ('VGA', 'RGB analog'),
  ('VGA', 'VGA analog'),
  ('GENLOCK', 'black burst'),
  ('GENLOCK', 'word clock video'),
  ('GENLOCK', 'reference sync'),
  ('GENLOCK', 'BNC sync'),
  ('FIBER', 'optical fiber'),
  ('FIBER', 'LC'),
  ('FIBER', 'SC'),
  ('FIBER', 'ST'),
  ('FIBER', 'SMPTE fiber'),
  ('FIBER', 'оптоволокно'),
  ('XLR', 'Cannon connector'),
  ('XLR', 'XLR3'),
  ('XLR', 'XLR5'),
  ('XLR', 'balanced audio'),
  ('RCA', 'phono'),
  ('RCA', 'composite video'),
  ('RCA', 'component video'),
  ('RCA', 'tulip'),
  ('JACK', '6.35mm jack'),
  ('JACK', '1/4 inch jack'),
  ('JACK', 'TRS'),
  ('JACK', 'TS'),
  ('XLR_JACK', 'combo jack'),
  ('XLR_JACK', 'XLR-jack combo input'),
  ('MINI_JACK', '3.5mm jack'),
  ('MINI_JACK', 'TRS mini'),
  ('MINI_JACK', 'aux'),
  ('AES_EBU', 'AES3'),
  ('AES_EBU', 'digital audio XLR'),
  ('AES_EBU', 'professional digital audio'),
  ('TOSLINK', 'S/PDIF optical'),
  ('TOSLINK', 'optical digital audio'),
  ('SPDIF_COAX', 'digital coax audio'),
  ('SPDIF_COAX', 'RCA digital audio'),
  ('SPEAKON', 'NL2'),
  ('SPEAKON', 'NL4'),
  ('SPEAKON', 'NL8'),
  ('SPEAKON', 'Neutrik Speakon'),
  ('DANTE', 'Audinate Dante'),
  ('DANTE', 'Dante AVIO'),
  ('DANTE', 'audio over IP'),
  ('AES67', 'audio over IP standard'),
  ('AES67', 'SMPTE ST 2110-30'),
  ('MIDI', '5-pin DIN'),
  ('MIDI', 'MIDI DIN'),
  ('DMX', 'DMX512'),
  ('DMX', '5-pin XLR lighting'),
  ('DMX', 'lighting control'),
  ('ARTNET', 'DMX over IP'),
  ('ARTNET', 'Art-Net protocol'),
  ('SACN', 'streaming ACN'),
  ('SACN', 'E1.31'),
  ('RS232', 'serial'),
  ('RS232', 'COM port'),
  ('RS232', 'DB9 serial'),
  ('RS485', 'serial bus'),
  ('RS485', 'differential serial'),
  ('ETHERNET', 'RJ45'),
  ('ETHERNET', 'Cat5'),
  ('ETHERNET', 'Cat5e'),
  ('ETHERNET', 'Cat6'),
  ('ETHERNET', 'Cat6a'),
  ('ETHERNET', 'LAN'),
  ('ETHERCON', 'Neutrik EtherCon'),
  ('ETHERCON', 'ruggedized RJ45'),
  ('USB', 'USB-A'),
  ('USB', 'USB-B'),
  ('USB', 'USB Mini'),
  ('USB', 'USB Micro'),
  ('USB_C', 'USB Type-C'),
  ('THUNDERBOLT', 'TB3'),
  ('THUNDERBOLT', 'TB4'),
  ('THUNDERBOLT', 'Thunderbolt 3'),
  ('THUNDERBOLT', 'Thunderbolt 4'),
  ('FIREWIRE', 'IEEE 1394'),
  ('FIREWIRE', 'i.Link'),
  ('FIREWIRE', 'FireWire 400'),
  ('FIREWIRE', 'FireWire 800'),
  ('LIGHTNING', 'Apple Lightning'),
  ('NDI', 'Network Device Interface'),
  ('NDI', 'NDI|HX'),
  ('NDI', 'video over IP'),
  ('POWER', 'mains'),
  ('POWER', 'AC power'),
  ('POWER', 'line power'),
  ('POWERCON', 'Neutrik PowerCon'),
  ('POWERCON', 'PowerCon TRUE1'),
  ('IEC', 'kettle plug'),
  ('IEC', 'C13'),
  ('IEC', 'C14'),
  ('IEC', 'C19'),
  ('IEC', 'C20'),
  ('IEC', 'IEC 60320'),
  ('SCHUKO', 'CEE 7/4'),
  ('SCHUKO', 'European plug'),
  ('SCHUKO', 'Schuko plug'),
  ('EDISON', 'NEMA 5-15'),
  ('EDISON', 'stage pin'),
  ('EDISON', 'Edison plug'),
  ('BANANA', '4mm banana plug'),
  ('BANANA', 'banana connector'),
  ('TERMINAL_BLOCK', 'Phoenix connector'),
  ('TERMINAL_BLOCK', 'screw terminal'),
  ('TERMINAL_BLOCK', 'barrier strip'),
  ('WIRELESS', 'RF link'),
  ('WIRELESS', 'wireless link'),
  ('WIRELESS', 'radio'),
  ('WIFI', 'WLAN'),
  ('WIFI', '802.11'),
  ('BLUETOOTH', 'BT'),
  ('BLUETOOTH', 'Bluetooth LE');

INSERT INTO connector_type_carriers (protocol_code, physical_code) VALUES
  ('DANTE', 'ETHERNET'),
  ('AES67', 'ETHERNET'),
  ('ARTNET', 'ETHERNET'),
  ('SACN', 'ETHERNET'),
  ('NDI', 'ETHERNET');
